export const BRAND = {
  name: "RETHINK",
  tagline: "No permission required.",
  // ponytail: launch-city enum per spec (no Mumbai in V1). Keep in sync with the `city` DB enum.
  cities: ["Bangalore", "Pune", "Delhi", "Hyderabad"],
  hero: {
    heading: "Three meetups. One open seat.",
    authCard: "Reserve a spot",
    authButton: "SEND CODE",
  },
  feed: {
    upcoming: "UPCOMING",
    happeningNow: "HAPPENING NOW",
  },
  dashboard: {
    hosting: "HOSTING",
    attending: "YOU'RE IN",
    emptyCommitments: "Nothing on your calendar yet. Pick something below.",
    manage: "MANAGE →",
  },
  rsvp: {
    going: "I'M GOING",
    cancel: "CAN'T MAKE IT",
  },
  create: {
    header: "NEW EVENT",
    status: "STATUS: DRAFT",
    publish: "PUBLISH EVENT",
    descriptionPlaceholder: "What's going down?",
  },
  empty: {
    feed: "Nothing on tonight. Build one.",
    myEvents: "You haven't signed up for anything yet.",
    hostEvents: "No events created yet.",
  },
  errors: {
    generic: "Something broke. Reload.",
    network: "Couldn't connect. Try again.",
    loadFailed: "Couldn't load events. Try again.",
    notFound: "This event doesn't exist.",
    past: "This event has passed.",
    full: "This event is full.",
  },
  run: {
    checkIn: "CHECK IN",
    uncheckIn: "UNDO",
    broadcast: "SEND BROADCAST",
    alreadySent: "ALREADY SENT",
    noAttendees: "No attendees yet.",
    broadcastPlaceholder: "Message to all attendees...",
  },
  feedback: {
    heading: "How was it?",
    subheading: "Your feedback goes directly to the organiser.",
    thumbsUp: "Yes, great",
    thumbsDown: "Could be better",
    notePlaceholder: "Anything else you'd like to share? (optional)",
    submitLabel: "SUBMIT FEEDBACK",
    alreadySubmitted: "You've already left feedback for this event.",
    noFeedback: "No feedback yet.",
    hostHeading: "FEEDBACK",
  },
  admin: {
    whitelistHeading: "HOST WHITELIST",
    whitelistHint: "Whitelisted emails can create events. Everyone on this list, and only this list.",
    whitelistPlaceholder: "member@example.com",
    whitelistAdd: "ADD",
    whitelistRemove: "REMOVE",
    whitelistEmpty: "Nobody can host yet. Add the first email.",
  },
  manifesto: "We don't do panels. We do arguments. Bring data or leave.",
  footer: {
    links: ["TERMS", "PRIVACY", "CAREERS", "CONTACT"],
    copyright: "No permission required.",
  },
} as const;
