export const BRAND = {
  name: "RETHINK",
  tagline: "No permission required.",
  cities: ["Bangalore", "Mumbai", "Pune", "Hyderabad", "Delhi"],
  hero: {
    heading: "Amazing events. Amazing people. Amazing chats.",
    authCard: "LOG IN TO THE RETHINKVERSE NOW!",
    authButton: "SEND CODE",
  },
  feed: {
    upcoming: "UPCOMING",
    happeningNow: "HAPPENING NOW",
  },
  rsvp: {
    going: "I'M GOING",
    cancel: "CAN'T MAKE IT",
    externalRegister: "REGISTER ON HOST'S PAGE",
    externalRegistered: "REGISTERED. OPEN PAGE",
    leaveWaitlist: "LEAVE WAITLIST",
    onWaitlist: "YOU'RE ON THE WAITLIST",
    waitlistPosition: (n: number) => `POSITION ${n} IN QUEUE`,
  },
  create: {
    header: "NEW EVENT",
    status: "STATUS: DRAFT",
    publish: "PUBLISH EVENT",
    descriptionPlaceholder: "What's going down?",
    trustedPublished: "YOUR EVENT IS LIVE.",
    pendingReview: "FIRST EVENT GOES THROUGH REVIEW. AFTER THAT YOU PUBLISH INSTANTLY.",
  },
  lifecycle: {
    inReview:  "IN REVIEW",
    live:      "LIVE",
    full:      "FULL",
    cancelled: "THIS EVENT WAS CANCELLED",
    ended:     "THIS EVENT HAS ENDED",
    rejected:  "REJECTED",
    pendingBanner: "ONLY YOU AND ADMINS CAN SEE THIS EVENT WHILE IT IS IN REVIEW.",
    checkedIn: "CHECKED IN",
  },
  admin: {
    trust: {
      grant:    "GRANT TRUST",
      revoke:   "REVOKE TRUST",
      trusted:  "TRUSTED HOST",
      untrusted: "UNTRUSTED",
    },
    cancel: {
      button:      "CANCEL EVENT",
      dialogTitle: "CANCEL THIS EVENT",
      dialogBody:  "This cannot be undone. All registered attendees will be notified.",
      reasonLabel: "REASON (required)",
      confirm:     "CANCEL EVENT",
      abort:       "KEEP EVENT",
    },
    checkIn: {
      checkIn:   "CHECK IN",
      checkedIn: "CHECKED IN",
      undo:      "UNDO",
    },
    featuredFor: {
      heading:     "FEATURE FOR AUDIENCE",
      activeBadge: "ACTIVE",
      goalLabel:   "GOAL",
      levelLabel:  "LEVEL",
      cityLabel:   "CITY",
      noneOption:  "— None —",
      saveButton:  "FEATURE EVENT",
      savedButton: "SAVED",
      clearButton: "CLEAR",
    },
  },
  ticket: {
    confirmed: "YOU'RE IN",
    waitlisted: "YOU'RE ON THE WAITLIST",
    addToCalendar: "ADD TO GOOGLE CALENDAR",
    downloadIcs: "DOWNLOAD .ICS",
    shareWhatsapp: "SHARE ON WHATSAPP",
    backToEvent: "BACK TO EVENT",
    noQr: "NO QR FOR WAITLISTED SPOTS. YOU'LL GET ONE WHEN A SPOT OPENS.",
  },
  updates: {
    header: "HOST UPDATES",
    emptyHost: "NO UPDATES SENT YET. ATTENDEES GET THESE BY EMAIL.",
    placeholder: "TYPE YOUR UPDATE HERE (MAX 1000 CHARS)...",
    sendButton: "SEND UPDATE",
    cooldown: (secs: number) => `WAIT ${secs}S`,
  },
  share: {
    button: "SHARE EVENT",
  },
  empty: {
    feed: "Nothing on tonight. Build one.",
    myEvents: "You haven't signed up for anything yet.",
  },
  errors: {
    generic: "Something broke. Reload.",
    network: "Couldn't connect. Try again.",
    loadFailed: "Couldn't load events. Try again.",
    notFound: "This event doesn't exist.",
    past: "This event has passed.",
    full: "This event is full.",
  },
  profile: {
    headingNew: "WHO ARE YOU?",
    headingGoalOnly: "ONE LAST THING.",
    namePlaceholder: "Your name",
    goalLabel: "WHAT ARE YOU HERE FOR?",
    levelLabel: "WHERE ARE YOU IN YOUR JOURNEY?",
    submit: "LET'S GO",
    submitting: "SAVING...",
    goals: [
      { value: "break_into_pm",  label: "Breaking into Product" },
      { value: "grow_as_pm",     label: "Growing as a PM" },
      { value: "build_products", label: "Building my own products" },
      { value: "ai_pm",          label: "AI & Product Management" },
      { value: "interview_prep", label: "PM Interview Prep" },
    ],
    levels: [
      { value: "aspiring", label: "Aspiring PM (0–1 yrs)" },
      { value: "early",    label: "Early PM (1–3 yrs)" },
      { value: "mid",      label: "Mid-level PM (3–5 yrs)" },
      { value: "senior",   label: "Senior PM (5+ yrs)" },
    ],
  },
  tags: {
    label: "TAG (OPTIONAL)",
    none: "None",
    options: [
      { value: "beginner",       label: "Beginner" },
      { value: "interview-prep", label: "Interview Prep" },
      { value: "ai-pm",          label: "AI & PM" },
      { value: "build",          label: "Build" },
      { value: "resume",         label: "Resume" },
    ],
  },
  forYou: {
    sectionTitle: "For you",
    cohortBadge: (n: number) => `${n} FROM YOUR COHORT`,
    empty: "NO EVENTS MATCH YOUR PROFILE YET.",
  },
  manifesto: "We don't do panels. We do arguments. Bring data or leave.",
  footer: {
    links: ["TERMS", "PRIVACY", "CAREERS", "CONTACT"],
    copyright: "\u00A92024 RETHINK EVENTS. NO PERMISSION REQUIRED.",
  },
} as const;
