export const BRAND = {
  name: "RETHINK",
  tagline: "No permission required.",
  cities: ["Bangalore", "Mumbai", "Pune", "Hyderabad", "Delhi"],
  hero: {
    heading: "Amazing events. Amazing people. Amazing chats.",
    authCard: "LOG IN TO THE RETHINKVERSE NOW!",
    authButton: "SEND CODE",
  },
  feed: {
    upcoming: "UPCOMING",
    happeningNow: "HAPPENING NOW",
  },
  rsvp: {
    going: "I'M GOING",
    cancel: "CAN'T MAKE IT",
    externalRegister: "REGISTER ON HOST'S PAGE",
    externalRegistered: "REGISTERED. OPEN PAGE",
  },
  create: {
    header: "NEW EVENT",
    status: "STATUS: DRAFT",
    publish: "PUBLISH EVENT",
    descriptionPlaceholder: "What's going down?",
    trustedPublished: "YOUR EVENT IS LIVE.",
    pendingReview: "FIRST EVENT GOES THROUGH REVIEW. AFTER THAT YOU PUBLISH INSTANTLY.",
  },
  lifecycle: {
    inReview:  "IN REVIEW",
    live:      "LIVE",
    full:      "FULL",
    cancelled: "THIS EVENT WAS CANCELLED",
    ended:     "THIS EVENT HAS ENDED",
    rejected:  "REJECTED",
    pendingBanner: "ONLY YOU AND ADMINS CAN SEE THIS EVENT WHILE IT IS IN REVIEW.",
  },
  admin: {
    trust: {
      grant:    "GRANT TRUST",
      revoke:   "REVOKE TRUST",
      trusted:  "TRUSTED HOST",
      untrusted: "UNTRUSTED",
    },
    cancel: {
      button:      "CANCEL EVENT",
      dialogTitle: "CANCEL THIS EVENT",
      dialogBody:  "This cannot be undone. All registered attendees will be notified.",
      reasonLabel: "REASON (required)",
      confirm:     "CANCEL EVENT",
      abort:       "KEEP EVENT",
    },
  },
  empty: {
    feed: "Nothing on tonight. Build one.",
    myEvents: "You haven't signed up for anything yet.",
  },
  errors: {
    generic: "Something broke. Reload.",
    network: "Couldn't connect. Try again.",
    loadFailed: "Couldn't load events. Try again.",
    notFound: "This event doesn't exist.",
    past: "This event has passed.",
    full: "This event is full.",
  },
  manifesto: "We don't do panels. We do arguments. Bring data or leave.",
  footer: {
    links: ["TERMS", "PRIVACY", "CAREERS", "CONTACT"],
    copyright: "\u00A92024 RETHINK EVENTS. NO PERMISSION REQUIRED.",
  },
} as const;
